version: "3.9"
services:

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./config/nginx-site.conf:/etc/nginx/conf.d/default.conf
      - ./www:/usr/share/nginx/html:rw

  php:
    image: tinpotnick/php:7.4.30-0.0.1
    volumes:
      - ./config/php.ini:/etc/php/php.ini
      - ./config/php-fpm.conf:/etc/php/php-fpm.conf
      - ./www:/usr/share/nginx/html:rw

